// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqtuhlaragbgtztblaen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxdHVobGFyYWdiZ3R6dGJsYWVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MTY5NzEsImV4cCI6MjA3MzI5Mjk3MX0._bMuRzMRRJeEzNNUhPYwZBpUh2iXqxga-lIj4iPw_WA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});